@startuml じゃらじゃら

actor "ユーザ" as User

User -> Alexa: じゃらじゃらを開いて

User <-- Alexa: 点数を教えてと、言ってください

note left User
  役割、符、翻を指定しない場合
end note

User -> Alexa: 点数を教えて

User <-- Alexa: 親ですか？子ですか？

User -> Alexa: 親

User <-- Alexa: 何符ですか？

User -> Alexa: 30符

User <-- Alexa: 何翻ですか？

User -> Alexa: ウーハン

User <-- Alexa: 30符5翻の点数は、満貫です。ツモは4000点オール。ロンは12,000点です。

@enduml
